[{
        "key": "B00OWEHFOLEWIFJ",
        "category": "furniture",
        "sub-category": "wardrobe",
        "name": "RFL Wardrobe Double 5D KD Elegant Maple Wood",
        "seller": "RFL",
        "stock": 36,
        "gender": "male",
        "star": 5,
        "starCount": 3245,
        "images": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrA6KCHbB23szE_ywcFkgtPVFo0vrDDSLqNw&usqp=CAU",
            "https: //encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSSSnbTBiQiZA09qmUDINO0gbrSL2a1gp4jw&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3E4_7__t4xuIMMlssnvVurqVf8gigkOMPWQ&usqp=CAU"
        ],
        "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyT8ljsQ_ntDa7DdD5Ci-aEa5c2rX22qIKTQ&usqp=CAU",
        "comments": [{ "description": "asdpadgspdgsdpgsdg sdg ", "rating": "3" }],
        "price": 68.36,
        "shipping": 7.99,
        "percentagePrice": 75,
    },
    {
        "key": "LSDFJOECL8IYK",
        "category": "furniture",
        "sub-category": "dining table",
        "name": "Dining Table 6 Seat Elegant S/L Prin Majesty Black",
        "seller": "RFL Dining Table",
        "stock": 606,
        "gender": "male",
        "star": 4.4,
        "starCount": 345,
        "images": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBP8GKE_G8y0-m_MNnV7c5uBLViaqKQV-mwA&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAgTGw1wXRm-tJcPwEmY5usME67kdYK6660Q&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRocB98zPeYeTuBN8GO-qoNRwQcz7tL3fWkVw&usqp=CAU"
        ],
        "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7F-IWn0Fh-nvzYWe9GVP-YXPEWTKqZMM5RacyXiq7oICrBsFNHLxYueeFJzhhvFp7sVQ&usqp=CAU",
        "comments": [{ "description": "asdpadgspdgsdpgsdg sdg ", "rating": "3" }],
        "price": 468,
        "shipping": 9.99,
        "percentagePrice": 400,
    },
    {
        "key": "B002REOIJCVCJOJRD",
        "category": "furniture",
        "sub-category": "bed",
        "name": "Regal Eden Wooden Double Bed",
        "seller": "Regal",
        "stock": 363,
        "gender": "male",
        "star": 5,
        "starCount": 325,
        "images": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdMvs7EAAmZyuujJsw0SVABihNkzh7Eg7iEw&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGHD17t1Whig6SlwuqIgIlcAgKPhapGSsoZw&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYjunTgxLeKRN7f8L5P4h5MoCaHPNbpTG9OA&usqp=CAU"
        ],
        "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUFUovAUpiC0wCY5juref-hpYq8hGNXYnc8A&usqp=CAU",
        "comments": [{ "description": "asdpadgspdgsdpgsdg sdg ", "rating": "3" }],
        "price": 46536,
        "shipping": 50,
        "percentagePrice": 46700,
    },
    {
        "key": "LEWJOIVJOWERJOE",
        "category": "furniture",
        "sub-category": "sofa",
        "name": "Regal Foam Sofa Cum Bed (Single)",
        "seller": "Regal",
        "stock": 26,
        "gender": "male",
        "star": 4.5,
        "starCount": 325,
        "images": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7voRXrk9CJD7SyJ3Hxzc_RmvAMi9G8ZhD5w&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcmLXwlIcAV43Y2YDa1M2yAIbVPzeMIdwbWg&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjS3789vP4zd2hGXsoapprTPuuRCVSd4ouOA&usqp=CAU"
        ],
        "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBKYzBeZl-q-oWR5VXwHq8T5qfwpk0TF7u_g&usqp=CAU",
        "comments": [{ "description": "asdpadgspdgsdpgsdg sdg ", "rating": "3" }],
        "price": 890,
        "shipping": 79,
        "percentagePrice": 975,
    },
    {
        "key": "B002RL8IYK",
        "category": "furniture",
        "sub-category": "Tool",
        "name": "Plastic Kitchen Stool - 53212548",
        "seller": "RFL",
        "stock": 6,
        "gender": "male",
        "star": 5,
        "starCount": 32,
        "images": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI1kC5usMFWfLGLH7qgaQeV-ryP-cDUu8N9Q&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIAY4vZ5s7QnY8A4b9fF2xAPw5JEaz-1ZWJg&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwhUIuPhk06q3VIXB0BfS44kFe5hD9lvTwag&usqp=CAU"
        ],
        "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9WvzPnMq7dxLplIXuDHlJQhESIx8scIJjNQ&usqp=CAU",
        "comments": [{ "description": "asdpadgspdgsdpgsdg sdg ", "rating": "3" }],
        "price": 62,
        "shipping": 3.99,
        "percentagePrice": 65,
    },
    {
        "key": "B002RL8IYK",
        "category": "furniture",
        "sub-category": "hanger",
        "name": "Universal 3 Layers Clothes Hanger",
        "seller": "STEEL",
        "stock": 96,
        "gender": "male",
        "star": 4.3,
        "starCount": 245,
        "images": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSu8hzNkQTh-KhUBqP4VBAqCIJz6ymmqntHSA&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQevtHWs07rXnCNTDBAvnE_MjGOX-aMHH7KGQ&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2008WwQt1wVzzng3_eUQwgdecYeZsY-ri1Q&usqp=CAU"
        ],
        "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQy4zOxIaeA5DPsNbygzqeT2TBhNUcs5M219Q&usqp=CAU",
        "comments": [{ "description": "asdpadgspdgsdpgsdg sdg ", "rating": "3" }],
        "price": 368,
        "shipping": 5,
        "percentagePrice": 375,
    },
    {
        "key": "B00SLF6SDF248",
        "category": "furniture",
        "sub-category": "gaming chair",
        "name": "Fantech Alpha GC-182 Sakura Gaming Chair",
        "seller": "Fantech",
        "stock": 312,
        "gender": "male",
        "star": 4.9,
        "starCount": 35,
        "images": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJsCsWGuRiOZIgGN_XOsbk7NOPQA-OJPymWQ&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRziOOX3FcdVi8CVMg3fgl98VmI8bqvKUhHqQ&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWT800bWR7czd9WkeydKsqVjYm_CIOyyO6UA&usqp=CAU"
        ],
        "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_3Pr6Eyo3Qed3qraxIch3AAqPtir0VHAyNg&usqp=CAU",
        "comments": [{ "description": "asdpadgspdgsdpgsdg sdg ", "rating": "3" }],
        "price": 10400,
        "shipping": 90,
        "percentagePrice": 10541,
    },
    {
        "key": "DSFV5FFDSF6F",
        "category": "furniture",
        "sub-category": "chair",
        "name": "Stick Design Dining Chair EF-CH-02",
        "seller": "tom furniture",
        "stock": 30,
        "gender": "male",
        "star": 3.9,
        "starCount": 45,
        "images": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5_JYU8YK_TIo4NlkS5KeGntWF4H7xAMCBpw&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYPPPXmwQQ2A1PA4r-QWBfw88HIeyaH49JEQ&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR24wMYqfEcfDFXrPUGZDsFzdvF8rtMdzDtJA&usqp=CAU"
        ],
        "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKgUfMLUrdDoKKf7qzuVH8Ycb-VngjTsw4TFQ8nsxsqdX9rH7HeA50z7CiRuAyjsRL828&usqp=CAU",
        "comments": [{ "description": "asdpadgspdgsdpgsdg sdg ", "rating": "3" }],
        "price": 5340,
        "shipping": 16,
        "percentagePrice": 5380,
    },
    {
        "key": "VAEREF24F54FD4SF",
        "category": "furniture",
        "sub-category": "showcase",
        "name": "Canadian Oak Veneer Daliya Showcase EF-Daliya-01",
        "seller": "Tom ltd",
        "stock": 56,
        "gender": "male",
        "star": 4.3,
        "starCount": 35,
        "images": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTP-T0TQtMTGsnFsZb3r7Guq9FrylxAPs60Cw&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRH16aI9DZ1W4i3Nu9JH2-chVGwJFXhdoH5VA&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHWgcSpXsdLtemVoFNA6vB1rD96uaS7MJCWg&usqp=CAU"
        ],
        "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmlA05IIs6D2mVM9MLnuyz-QwFVcDng7px9g&usqp=CAU",
        "comments": [{ "description": "asdpadgspdgsdpgsdg sdg ", "rating": "3" }],
        "price": 58175,
        "shipping": 160,
        "percentagePrice": 58375,
    },
    {
        "key": "B002RL8IYK",
        "category": "furniture",
        "sub-category": "wardrobe",
        "name": "Storage Wardrobe 88130B",
        "seller": "priyo shop",
        "stock": 16,
        "gender": "male",
        "star": 4.6,
        "starCount": 5,
        "images": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2KLhAUqBfK3PP8rzL_c5jsQV0fJ6-zTIzdQ&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgyth0HQ-060weBbdrwxUs_8vf7wXaMwTc-A&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTH8hbI3FjxBmQeeiLse9FcqsrCFg5glpZVuw&usqp=CAU"
        ],
        "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjDX801rFENKsOD9AFZBdxbxRv-dcRL5NjOA&usqp=CAU",
        "comments": [{ "description": "asdpadgspdgsdpgsdg sdg ", "rating": "3" }],
        "price": 20324,
        "shipping": 90,
        "percentagePrice": 20434,
    },
]



// shoes - category

[{
        "key": "WOJV346VAF46EWVFSD3",
        "category": "shoes",
        "sub-category": "casual shoe",
        "name": "VENTURINI Men's Casual Shoe",
        "seller": "Apex",
        "stock": 56,
        "gender": "male",
        "star": 4.2,
        "starCount": 15,
        "images": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSybcw0-A2Bk0oD0_06v1nm-AicvivJTZ39BA&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgyth0HQ-060weBbdrwxUs_8vf7wXaMwTc-A&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1TONPdiZEhBjYQ2BfEoyS1P-4cSLZaymg6g&usqp=CAU"
        ],
        "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOz22VkuSWmjJAXpF1AcjgYqLf1f6gIiT3cQ&usqp=CAU",
        "comments": [{ "description": "asdpadgspdgsdpgsdg sdg ", "rating": "3" }],
        "price": 2004,
        "shipping": 10,
        "percentagePrice": 2024,
    },
    {
        "key": "AOJF3A4EFV6A4RFE1V",
        "category": "shoes",
        "sub-category": "sprint shoe",
        "name": "SPRINT Men's Canvas",
        "seller": "bata",
        "stock": 56,
        "gender": "male",
        "star": 4.6,
        "starCount": 51,
        "images": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3s10CbIw7fTN14tY_sIbfKffyc24oPZ7yFQ&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgyth0HQ-060weBbdrwxUs_8vf7wXaMwTc-A&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTFOhYEVYQfZMFZjLQaZhm0CO7XQL6JP6qPw&usqp=CAU"
        ],
        "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhDA8W4oo_po0i3P9u9pNczGdXtpxFcx6PKw&usqp=CAU",
        "comments": [{ "description": "asdpadgspdgsdpgsdg sdg ", "rating": "3" }],
        "price": 891,
        "shipping": 15,
        "percentagePrice": 910,
    },

    {
        "key": "C5VE4VSE5V4SE",
        "category": "shoes",
        "sub-category": "jutti woman",
        "name": "Walkar Ladies Jutti Red",
        "seller": "brando",
        "stock": 106,
        "gender": "female",
        "star": 4.8,
        "starCount": 65,
        "images": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4U-Ts_OQ_jgjUNom_ljwCwD5kQNNqjFo4dg&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwf3Ssua3JJygK4LeEXFms8NxKRLWPgq80VQ&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmZZMkVVIpiBWxh7uSk4eRYS7zFrGEdUI_VvxF_1IxgfVxSHWSrW8gua7D3klIGVXp1sw&usqp=CAU"
        ],
        "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSU5DzQYTscW1PBwEPNZkz33hh8RfffEHHCsw&usqp=CAU",
        "comments": [{ "description": "asdpadgspdgsdpgsdg sdg ", "rating": "3" }],
        "price": 1324,
        "shipping": 90,
        "percentagePrice": 1344,
    },
    {
        "key": "IBLHUG5448F4R",
        "category": "shoes",
        "sub-category": "tassel shoe",
        "name": "Men's Stylish Tassel Shoe Brown",
        "seller": "brando",
        "stock": 236,
        "gender": "male",
        "star": 4.9,
        "starCount": 90,
        "images": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0abn3Z4fuPaNmsW-DKBNzvMSwhRNgiMEJKg&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzR7lXmtMfZssYgq099UgDqzc11l3MuXFCtw&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzcNJbNOewLQNmaXSbSBfPmYq1C3K_kjA4CQ&usqp=CAU"
        ],
        "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSRAE9PbmEnOrc8QoixVObKvSKThOJWfNbOg&usqp=CAU",
        "comments": [{ "description": "asdpadgspdgsdpgsdg sdg ", "rating": "3" }],
        "price": 1824,
        "shipping": 13,
        "percentagePrice": 1860,
    },
    {
        "key": "54SDV5ARFV5F4",
        "category": "shoes",
        "sub-category": "summer sandal",
        "name": "Bay Men's Summer Sandal Mixed",
        "seller": "Bay bengol",
        "stock": 41,
        "gender": "male",
        "star": 5,
        "starCount": 55,
        "images": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSzBBaMJEnbsSNdx9xilYnohoIR49AiDQGIeA&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJMTRBEdtPbaPs5PR7KZVHDBf7StwEJEatzg&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTcu0FgQNapIK8I0eRul7rC5Kp5CD_1xy4aA&usqp=CAU"
        ],
        "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbEzzGxRCnnqqKL6PyDiAu-UNCApApaFAwMA&usqp=CAU",
        "comments": [{ "description": "asdpadgspdgsdpgsdg sdg ", "rating": "3" }],
        "price": 2544,
        "shipping": 20,
        "percentagePrice": 2580,
    },
    {
        "key": "D5EV5YH5DF1HE",
        "category": "shoes",
        "sub-category": "float shoe",
        "name": "Lara Clara Ladies Open Flats",
        "seller": "KMD limited",
        "stock": 26,
        "gender": "female",
        "star": 4.8,
        "starCount": 35,
        "images": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSK8tv5Lhx0Vu115jWkr4JKtf3GxV31e6ledQ&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLJMhQWT1-znbxopttExQ6SuH8VzqwPkz9rg&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeWdo8TzN2kol0Mmv3fndTZsMjrv1fm9c3ng&usqp=CAU"
        ],
        "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgdMWIly6_00THed0JuSPz-t5AuAfUUd3ODw&usqp=CAU",
        "comments": [{ "description": "asdpadgspdgsdpgsdg sdg ", "rating": "3" }],
        "price": 3224,
        "shipping": 40,
        "percentagePrice": 3289,
    },
    {
        "key": "SG464S64T1ERREF1",
        "category": "shoes",
        "sub-category": "ladies sandal",
        "name": "Ladies Wedge Back Belt Sandal Red",
        "seller": "walker",
        "stock": 12,
        "gender": "female",
        "star": 5,
        "starCount": 35,
        "images": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcYqCH6xZDr_RTdUU_tYIfQcy2kEcKkT-2qA&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQ1cponVsoHPdHQG8p2dAoJabi624D95PA2w&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvgfyo8BdIt7eTFKT_syGiUvvwhNy1EXZspQ&usqp=CAU"
        ],
        "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHquhxWGfRgdGcSVM6EncTqvU_vsFLExPpNA&usqp=CAU",
        "comments": [{ "description": "asdpadgspdgsdpgsdg sdg ", "rating": "3" }],
        "price": 4324,
        "shipping": 90,
        "percentagePrice": 4415,
    },
    {
        "key": "VBOG25446REVGD5FG",
        "category": "shoes",
        "sub-category": "choppol",
        "name": "Victori One Logo Print Sliders",
        "seller": "nike",
        "stock": 42,
        "gender": "male",
        "star": 3.6,
        "starCount": 5,
        "images": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2AzEYdr_Va4P_TSQ4AgE8A1dpBnINnbaA2Q&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJmbZfVDdnDL0lFc-8W1BBvBttDAjhP0R9pQ&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTX9UrOwEM2azOsYzdf1iGJTXUA_Ylkm5m4Kw&usqp=CAU"
        ],
        "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_BaXHjjU51WI1MW40pNW0xuimUuH730_-fg&usqp=CAU",
        "comments": [{ "description": "asdpadgspdgsdpgsdg sdg ", "rating": "3" }],
        "price": 1024,
        "shipping": 10,
        "percentagePrice": 1103,
    },
    {
        "key": "5BAREHRC54R1G4CFR",
        "category": "shoes",
        "sub-category": "sneaker",
        "name": "Panal Colourblock Lace-Up Sneakers",
        "seller": "MSB ltd",
        "stock": 66,
        "gender": "male",
        "star": 5,
        "starCount": 75,
        "images": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYJIIZOs3GXKZ5bKAjltBXc8-BiFfrrBsiBw&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStIGvJoe-ff5vHEFYJQxPu2akv1YHgmEwHUg&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwYF2GK8OqrqnjCtEeR7NDe9Y7buvJyfQQUQ&usqp=CAU"
        ],
        "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcQYcN9SU-1lq1wePxVO2qhXeCuHCdlPtvpw&usqp=CAU",
        "comments": [{ "description": "asdpadgspdgsdpgsdg sdg ", "rating": "3" }],
        "price": 2324,
        "shipping": 60,
        "percentagePrice": 2434,
    },
    {
        "key": "4SF4F64WRV46SDF4SF",
        "category": "shoes",
        "sub-category": "boots",
        "name": "Ankle-Length Lace-Up Boots",
        "seller": "ankly",
        "stock": 66,
        "gender": "male",
        "star": 4.9,
        "starCount": 25,
        "images": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ--Q8cpTVpkCUbRl8pW1bYj0PHrUxbK6-b_g&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTT7HPAU5YrUYTbVXRQbsQz79RuMbP_lvvVag&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREG2htZLc93JNzBxTMvB_-LuSX7Dcy7H8-0A&usqp=CAU"
        ],
        "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVsM9JuvIFP5c_r9AMoXbiFFDeixgx1K5skg&usqp=CAU",
        "comments": [{ "description": "asdpadgspdgsdpgsdg sdg ", "rating": "3" }],
        "price": 1524,
        "shipping": 20,
        "percentagePrice": 1580,
    }
]


// technology--------------------------------------------------------


[{
        "key": "B002RL8IYK",
        "category": "technology",
        "sub-category": "laptop",
        "name": "Asus UQ34312",
        "seller": "3M",
        "stock": 36,
        "gender": "men",
        "star": 3,
        "starCount": 3245,
        "images": ["https://images-na.ssl-images-amazon.com/images/I/415oziPFA0L._AC_US218_.jpg", "https://www.notebookcheck.net/fileadmin/Notebooks/Asus/Zenbook_UX3430UQ-GV012T/4zu3_Asus_Zenbook_UX3430UQ_Teaser.jpg", "https://www.nexus.com.bd/images/detailed/2/ux430uq-gold_Metal.png"],
        "comments": [{
                "description": "Very good performance. Loved the color ",
                "rating": "3"
            }

        ],
        "price": 68.36,
        "shipping": 7.99,
        "percentagePrice": 75,
    },
    {
        "key": "B01LZ2WZGH",
        "category": "technology",
        "sub-category": "laptop",
        "name": "Hp el24w",
        "seller": "Manfrotto",
        "gender": "men",
        "stock": 55,
        "star": 2,
        "starCount": 2899,
        "images": ["https://in-media.apjonlinecdn.com/catalog/product/cache/b3b166914d87ce343d4dc5ec5117b502/c/0/c07145111.png", "https://www.hp.com/gb-en/shop/Html/Merch/Images/c06751173_390x286.jpg", "https://i.gadgets360cdn.com/large/HP_Pavilion_Aero_13_launch_1625031929744.jpg?downsize=950:*"],
        "comments": [{
                "description": "satisfactory performance. blue color should be available  ",
                "rating": "4"
            }

        ],
        "price": 169.88,
        "shipping": 3.99,
        "percentagePrice": 181,

    },
    {
        "key": "B01K1IO3QW",
        "category": "technology",
        "sub-category": "laptop",
        "name": "Acer Aspire E 15",
        "seller": "Acer",
        "gender": "women",
        "stock": 3,
        "star": 3,
        "starCount": 3525,
        "images": ["https://images-na.ssl-images-amazon.com/images/I/41HfDkXXyeL._AC_US218_.jpg", "https://static.acer.com/up/Resource/Acer/Laptops/Aspire_5/photogallery/20200916/Acer-Aspire-5_A515-56-56G-56S-56T_with-FP-Backlit_Silver_gallery_01.png", "https://i.ytimg.com/vi/Bze6HJg1xWs/maxresdefault.jpg"],
        "comments": [{
                "description": "below average. ",
                "rating": "2"
            }

        ],
        "price": 349.99,
        "shipping": 3.99,
        "percentagePrice": 381,

    },
    {
        "key": "B01LD4MGY4",
        "category": "technology",
        "sub-category": "laptop",
        "name": "Acer E5-575G-57D4 15.6-Inches",
        "seller": "Acer",
        "gender": "women",
        "stock": 49,
        "star": 4,
        "starCount": 4232,
        "images": ["https://images-na.ssl-images-amazon.com/images/I/41HfDkXXyeL._AC_US218_.jpg", "https://www.windowscentral.com/sites/wpcentral.com/files/field/image/2019/01/acer-aspire-e-15-cropped-01.png?itok=0ZeNgEaQ", "https://i.gadgets360cdn.com/large/HP_Pavilion_Aero_13_launch_1625031929744.jpg?downsize=950:*"],
        "comments": [{
                "description": "satisfactory performance. blue color should be available  ",
                "rating": "4"
            }

        ],
        "price": 579.99,
        "shipping": 7.99,
        "percentagePrice": 615

    },
    {
        "key": "B01M18UZF5",
        "category": "technology",
        "sub-category": "laptop",
        "name": "ASUS ZenBook",
        "seller": "Asus",
        "gender": "child",
        "stock": 23,
        "star": 4,
        "starCount": 2457,
        "images": ["https://images-na.ssl-images-amazon.com/images/I/417yCr3mvYL._AC_US218_.jpg", "https://static.acer.com/up/Resource/Acer/Laptops/Nitro_5/rev-jan-2021-intel/20210329/Acer-Nitro5-KSP1-640.jpg", "https://static.acer.com/up/Resource/Acer/Laptops/Aspire_3/rev-jan-2021/20210318/KSP1_640.jpg"],
        "comments": [{
                "description": "satisfactory. blue color should be available  ",
                "rating": "4"
            }

        ],
        "price": 699,
        "shipping": 3.99,
        "percentagePrice": 720

    },
    {
        "key": "B01DBGVB7K",
        "category": "technology",
        "sub-category": "laptop",
        "name": "ASUS Chromebook",
        "seller": "Asus",
        "gender": "child",
        "stock": 54,
        "star": 4,
        "starCount": 2777,
        "images": ["https://images-na.ssl-images-amazon.com/images/I/31inMpRxCFL._AC_US218_.jpg", "https://www.google.com/chromebook/assets-2019/static/images/chrome-os/Simplicity_MeetChomeOS@2x.jpg", "https://www.notebookcheck.net/typo3temp/_processed_/6/9/csm_2002462588_01_36237551de.jpg"],
        "comments": [{
                "description": "satisfactory. blue color should be available  ",
                "rating": "4"
            }

        ],
        "price": 220.49,
        "shipping": 3.99,
        "percentagePrice": 250

    },
    {
        "key": "B0713WPJKX",
        "category": "technology",
        "sub-category": "android",
        "name": "Nokia XS123",
        "seller": "Cell-Tronics",
        "gender": "all",
        "stock": 87,
        "star": 4,
        "starCount": 3392,
        "images": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4Ownc4L1v8rPjCN5EKnEalcNQhApNQ0t1myjk8zL-d8y9k8_-KO0IzDc41Kpvx_QMTkE&usqp=CAU", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOA59JiFZJXFuRYkEqD2N5IBSHfuW_qFSUtREG4wusRlCAm1DKYXKsW1lm0Sr8dU1sCXQ&usqp=CAU", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDm2Thexm64-yYmk9vO7L9o4wx0WqMb02aySR8Pir9qlArd8XjoRueDhbpxi8_yJ0KOlI&usqp=CAU"],
        "comments": [{
                "description": "satisfactory. blue color should be available  ",
                "rating": "4"
            }

        ],
        "price": 10.99,
        "shipping": 3.99,
        "percentagePrice": 20

    },
    {
        "key": "B01LPZD1N6",
        "category": "technology",
        "sub-category": "android",
        "name": "Nokia  Ato2 ",
        "seller": "ATOTO",
        "gender": "men",
        "stock": 20,
        "star": 3,
        "starCount": 4029,
        "images": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkY6qwelNpeeB2Nr6w0hO-NFkjJZjjwWq_mW2iVLJSpdwLUR19bP69zo1RNrdAdU_3HKo&usqp=CAU", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQia18Uq4Vh6DFrI5XPmnOSx1i2giadelCadXT-HVakTcR70EDAs9CE63BQjBCcB3Lv1uY&usqp=CAU", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQNHSpjLiPDbAuDJrt3m6g4w7DGzTy18lXR4cLIbtWVr8DI50Ce-BH6TfRREZEVeTBiOI&usqp=CAU"],
        "comments": [{
                "description": "satisfactory. blue color should be available  ",
                "rating": "4"
            }

        ],
        "price": 164.9,
        "shipping": 0,
        "percentagePrice": 180

    },
    {
        "key": "B01N1SE4EP",
        "category": "technology",
        "sub-category": "android",
        "name": "Samsung Gx14",
        "seller": "NeuTab",
        "gender": "men",
        "stock": 50,
        "star": 3,
        "starCount": 4947,
        "images": ["https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s10-cardinal-red.jpg", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmGYrHu3p7-9kHSGIyxTopPUMrH13TDE-S2jihz1WEUAJiDWAZ1ScdN0Occ00lpspAgk4&usqp=CAU", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSElHvgzMjB2asDq6ao2TjjuOVy0Q4KxErNaxvL2TdSSMT2FDJwO7OAph1D0PpbOMhJmTU&usqp=CAU"],
        "comments": [{
                "description": "satisfactory. blue color should be available  ",
                "rating": "4"
            }

        ],
        "price": 49.99,
        "shipping": 7.99,
        "percentagePrice": 60

    },
    {
        "key": "B017LDNLIG",
        "category": "technology",
        "sub-category": "android",
        "name": "Tracfone Alcatel Onetouch Pixi Glitz A463BG",
        "seller": "Tracfone",
        "gender": "women",
        "stock": 85,
        "star": 3,
        "starCount": 381,
        "images": ["https://media.wired.com/photos/5e8d09b9798a15000821feb0/1:1/w_1800,h_1800,c_limit/Gear-Feature-Samsung-Galaxy-A51-front-SOURCE-Samsung.jpg", "https://www.androidcentral.com/sites/androidcentral.com/files/styles/large/public/article_images/2021/04/galaxy-a12.jpg", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQl8J0Dj-SF3ElxS6ZJQE2x6a7ypwnflUQIgLyeDqUJAVG22vA6znV-mdcvD4f610FARvw&usqp=CAU"],
        "comments": [{
                "description": "satisfactory. blue color should be available  ",
                "rating": "4"
            }

        ],
        "price": 19.94,
        "shipping": 7.99,
        "percentagePrice": 30

    }

]